### ISSUE TITLE
Use IPFS + cloudflare ipfs + ipfs.io for the package host.

### ISSUE THREAD

**Issue by crazyaccess** [MiMillieuh/Photoshop-CC2021-Linux#11]
You can use https://nft.storage and within 2 days the package will get dealt with permanently to a crypto hash that can be used with cloudflare's ipfs to https portal to download huge files.

**Comment by MiMillieuh** [comment]
Hey, thanks for the advice

I'll check that when I got some time ^^

**Comment by MoltarTheGreat** [comment]
Note that the AdobePhotoshop2021.tar.xz hosted [here](https://download854.mediafire.com/kj7h8gkorsvg/dhvztovo7gj738e/AdobePhotoshop2021.tar.xz) no longer works and the script will download the website rather than the file itself. I agree on using IPFS; it is extremely easy to use, especially with a pinning service like [pinata](https://www.pinata.cloud/) which can essentially make it effortless to upload files like this without fear of it being taken down or ever going stale (anything uploaded to IPFS can essentially be seen as being there forever and immutable so long as some node is still hosting the data, entirely decentralized)

@MiMillieuh

**Comment by crazyaccess** [comment]
@MoltarTheGreat thanks for the support. and I think I can help on working with this as a pull or something.

**Comment by crazyaccess** [comment]
But actually the certificate was expired a little while back of the main host site. I think that's what was causing that?

**Comment by MiMillieuh** [comment]
Hello guys, thanks for your answer and help. 

I now own a server so I can host photoshop on it. 

I just try to fix tar for next update and it should be good to go
